# Generated by Django 4.1.3 on 2022-11-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('barcode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=50)),
                ('service_description', models.CharField(max_length=150)),
                ('expiration', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash')], max_length=25)),
                ('card_number', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='api.payable')),
            ],
        ),
    ]
